More solr startup goodness.
- Add /etc/defaults/solr
- Add upstart script
- Add script to bootstrap a solr home
- Modify solr script to handle SOLR_USER etc.

diff --git a/solr/solr b/solr/solr
--- a/solr/solr
+++ b/solr/solr
@@ -4,14 +4,37 @@
 set -e
 
 # show usage
-[ $# -eq 0 -o "$1" = "--help" ] && {
+[ "$1" = "--help" ] && {
     grep '^#/'< "$0" |
     cut -c4-
     exit 2
 }
 
-SOLR_HOME=$1
-shift
+if [ `id -u` -ne 0 ]; then
+	echo "Solr needs superuser privileges, abort."
+	exit 1
+fi
+
+# Load SOLR_USER, SOLR_LOGDIR and SOLR_HOME from /etc/default/solr.
+[ -r /etc/default/solr ] && . /etc/default/solr
+
+SOLR_USER="${SOLR_USER:=nobody}"
+SOLR_LOGDIR="${SOLR_LOGDIR:=/var/log/solr}"
+
+if [ -n "$1" ]; then
+	SOLR_HOME=$1
+	shift
+fi
+
+if [ -z "$SOLR_HOME" ]; then
+	echo "SOLR_HOME is not set, abort."
+	exit 1
+fi
+
+if [ ! -d "$SOLR_HOME/conf" ]; then
+	echo "$SOLR_HOME/conf is missing. Please bootstrap $SOLR_HOME. Abort."
+	exit 1
+fi
 
 JAVA_OPTS="
   -Djetty.home=/usr/share/solr/jetty
@@ -21,4 +44,10 @@ JAVA_OPTS="
   -Xmx1024m
 "
 
-exec java $JAVA_OPTS -Dsolr.solr.home=$SOLR_HOME "$@" -jar /usr/share/solr/jetty/start.jar /usr/share/solr/jetty/etc/jetty.xml
+mkdir -p $SOLR_LOGDIR && chown -R $SOLR_USER $SOLR_LOGDIR
+mkdir -p $SOLR_HOME/data && chown -R $SOLR_USER $SOLR_HOME/data
+
+exec sudo -u $SOLR_USER java $JAVA_OPTS \
+	-Dsolr.solr.home=$SOLR_HOME "$@" \
+	-jar /usr/share/solr/jetty/start.jar \
+	/usr/share/solr/jetty/etc/jetty.xml >> $SOLR_LOGDIR/solr.log 2>&1
